"""
Antigravity Engine — Intent-Level Research Coding
====================================================
You operate at the level of Intent. Winnie handles the Gravity.

Three-Surface Architecture:
  1. Editor (Sync)  — Tab-to-Intent live coding
  2. Manager (Async) — Mission Control for autonomous agents
  3. Browser (Verify) — Automated output verification

Core Capabilities:
  - Tab-to-Intent: hypothesis → full statistical code
  - Artifact Plans: blueprint before execution
  - Self-Healing Scripts: auto-fix on failure
  - Thought Signatures: encrypted reasoning integrity
  - Research Memos: findings + citations, not raw output
  - Research Skill: learns your coding style
"""

import hashlib
import json
import logging
import os
import re
import subprocess
import threading
import time
from collections import deque
from datetime import datetime
from pathlib import Path
from typing import Optional

log = logging.getLogger("edith.antigravity")


# ═══════════════════════════════════════════════════════════════════
# §1: THOUGHT SIGNATURES — Reasoning Integrity Layer
# "Encrypted signature of internal reasoning before every step."
# ═══════════════════════════════════════════════════════════════════

class ThoughtSignature:
    """Prevents reasoning drift by signing every planning step.

    Each thought is hashed with the previous signature,
    forming an immutable chain of reasoning.
    """

    def __init__(self):
        self._chain: list[dict] = []
        self._current_hash = "GENESIS"

    def sign_thought(self, thought: str, grounding: list[str] = None) -> dict:
        """Sign a reasoning step and add it to the chain."""
        payload = {
            "step": len(self._chain) + 1,
            "thought": thought,
            "grounding": grounding or [],  # Sources from the vault
            "previous_hash": self._current_hash,
            "timestamp": datetime.now().isoformat(),
        }

        # Chain the hash
        sig_input = f"{self._current_hash}|{thought}|{json.dumps(grounding or [])}"
        signature = hashlib.sha256(sig_input.encode()).hexdigest()[:16]
        payload["signature"] = signature
        self._current_hash = signature

        self._chain.append(payload)
        return payload

    def verify_chain(self) -> dict:
        """Verify the entire reasoning chain for integrity."""
        if not self._chain:
            return {"valid": True, "steps": 0}

        prev = "GENESIS"
        for i, step in enumerate(self._chain):
            sig_input = f"{prev}|{step['thought']}|{json.dumps(step['grounding'])}"
            expected = hashlib.sha256(sig_input.encode()).hexdigest()[:16]
            if expected != step["signature"]:
                return {
                    "valid": False,
                    "broken_at": i + 1,
                    "expected": expected,
                    "got": step["signature"],
                }
            prev = step["signature"]

        return {"valid": True, "steps": len(self._chain)}

    def get_chain(self) -> list[dict]:
        return list(self._chain)

    def reset(self):
        self._chain = []
        self._current_hash = "GENESIS"


thought_signer = ThoughtSignature()


# ═══════════════════════════════════════════════════════════════════
# §2: TAB-TO-INTENT — Hypothesis → Full Statistical Code
# "You type a hypothesis, Winnie writes the entire model."
# ═══════════════════════════════════════════════════════════════════

# Pre-built intent templates for common PolSci research patterns
INTENT_TEMPLATES = {
    "multi_level_model": {
        "keywords": ["multi-level", "multilevel", "hierarchical", "nested", "xtmixed", "hlm"],
        "stata_template": (
            "* Multi-level model: {dv} ~ {ivs}\n"
            "* Generated by E.D.I.T.H. Antigravity Engine\n"
            "* Grounded in: {citations}\n\n"
            "use \"{data_path}\", clear\n\n"
            "* Descriptive statistics\n"
            "summarize {all_vars}\n\n"
            "* Check for collinearity\n"
            "regress {dv} {ivs}\n"
            "estat vif\n\n"
            "* Model 1: Random intercept\n"
            "xtmixed {dv} {ivs} || {level2}: , mle\n"
            "estimates store m1\n\n"
            "* Model 2: Random slope\n"
            "xtmixed {dv} {ivs} || {level2}: {random_slope}, mle cov(unstructured)\n"
            "estimates store m2\n\n"
            "* Compare models\n"
            "lrtest m1 m2\n\n"
            "* Diagnostics\n"
            "predict residuals, residuals\n"
            "histogram residuals, normal\n"
        ),
        "r_template": (
            "# Multi-level model: {dv} ~ {ivs}\n"
            "# Generated by E.D.I.T.H. Antigravity Engine\n"
            "# Grounded in: {citations}\n\n"
            "library(lme4)\n"
            "library(lmerTest)\n\n"
            "df <- read.csv(\"{data_path}\")\n\n"
            "# Model 1: Random intercept\n"
            "m1 <- lmer({dv} ~ {ivs_r} + (1 | {level2}), data = df, REML = FALSE)\n"
            "summary(m1)\n\n"
            "# Model 2: Random slope\n"
            "m2 <- lmer({dv} ~ {ivs_r} + ({random_slope} | {level2}), data = df, REML = FALSE)\n"
            "summary(m2)\n\n"
            "# Compare models\n"
            "anova(m1, m2)\n\n"
            "# ICC\n"
            "performance::icc(m1)\n"
        ),
    },
    "difference_in_differences": {
        "keywords": ["diff-in-diff", "did", "difference in difference", "treatment effect", "parallel trends"],
        "stata_template": (
            "* Difference-in-Differences: {dv}\n"
            "* Treatment: {treatment}, Post: {post_var}\n\n"
            "use \"{data_path}\", clear\n\n"
            "* Generate interaction\n"
            "gen treat_post = {treatment} * {post_var}\n\n"
            "* Basic DiD\n"
            "regress {dv} {treatment} {post_var} treat_post {controls}, robust\n\n"
            "* With fixed effects\n"
            "reghdfe {dv} treat_post {controls}, absorb({fe1} {fe2}) cluster({cluster_var})\n\n"
            "* Parallel trends test\n"
            "forvalues t = -3/3 {{\n"
            "    gen lead_lag_`t' = {treatment} * (year == treatment_year + `t')\n"
            "}}\n"
            "regress {dv} lead_lag_* {controls}, robust\n"
            "coefplot lead_lag_*\n"
        ),
        "r_template": (
            "# Difference-in-Differences: {dv}\n"
            "library(fixest)\n"
            "library(did)\n\n"
            "df <- read.csv(\"{data_path}\")\n\n"
            "# Two-way FE DiD\n"
            "m1 <- feols({dv} ~ {treatment}:{post_var} | {fe1} + {fe2}, data = df, cluster = ~{cluster_var})\n"
            "summary(m1)\n\n"
            "# Callaway-Sant'Anna (robust to heterogeneous effects)\n"
            "cs <- att_gt(yname = \"{dv}\", tname = \"year\", idname = \"{unit_id}\",\n"
            "             gname = \"treatment_year\", data = df)\n"
            "summary(cs)\n"
            "ggdid(cs)\n"
        ),
    },
    "regression_discontinuity": {
        "keywords": ["regression discontinuity", "rdd", "rd", "cutoff", "threshold", "running variable"],
        "stata_template": (
            "* Regression Discontinuity: {dv}\n"
            "* Running variable: {running_var}, Cutoff: {cutoff}\n\n"
            "use \"{data_path}\", clear\n\n"
            "* Center running variable\n"
            "gen running_c = {running_var} - {cutoff}\n"
            "gen treated = (running_c >= 0)\n\n"
            "* Sharp RD\n"
            "rdrobust {dv} running_c, c(0) all\n\n"
            "* Bandwidth selection\n"
            "rdbwselect {dv} running_c, c(0) all\n\n"
            "* McCrary density test\n"
            "rddensity running_c, c(0)\n\n"
            "* Visualization\n"
            "rdplot {dv} running_c, c(0) p(1)\n"
        ),
        "r_template": (
            "# Regression Discontinuity: {dv}\n"
            "library(rdrobust)\n"
            "library(rddensity)\n\n"
            "df <- read.csv(\"{data_path}\")\n"
            "df$running_c <- df${running_var} - {cutoff}\n\n"
            "# Sharp RD\n"
            "rd <- rdrobust(df${dv}, df$running_c, c = 0)\n"
            "summary(rd)\n\n"
            "# McCrary density test\n"
            "dens <- rddensity(df$running_c, c = 0)\n"
            "summary(dens)\n\n"
            "rdplot(df${dv}, df$running_c, c = 0, p = 1)\n"
        ),
    },
    "instrumental_variables": {
        "keywords": ["instrumental variable", "iv", "2sls", "two-stage", "instrument", "endogeneity"],
        "stata_template": (
            "* Instrumental Variables: {dv}\n"
            "* Endogenous: {endogenous}, Instrument: {instrument}\n\n"
            "use \"{data_path}\", clear\n\n"
            "* First stage\n"
            "regress {endogenous} {instrument} {controls}, robust\n"
            "test {instrument}\n"
            "* F > 10 required (Staiger-Stock)\n\n"
            "* 2SLS\n"
            "ivregress 2sls {dv} {controls} ({endogenous} = {instrument}), robust first\n\n"
            "* Diagnostics\n"
            "estat firststage\n"
            "estat overid\n"
            "estat endogenous\n"
        ),
        "r_template": (
            "# Instrumental Variables: {dv}\n"
            "library(AER)\n"
            "library(fixest)\n\n"
            "df <- read.csv(\"{data_path}\")\n\n"
            "# 2SLS\n"
            "m1 <- feols({dv} ~ {controls} | 0 | {endogenous} ~ {instrument}, data = df)\n"
            "summary(m1)\n"
            "fitstat(m1, type = \"ivf\")\n"
        ),
    },
}


def tab_to_intent(
    intent: str,
    language: str = "stata",
    data_path: str = "",
    model_chain: list[str] = None,
) -> dict:
    """Convert a research intent into complete statistical code.

    "Test if charity density affects SNAP enrollment using multi-level model"
    → Full Stata/R script with diagnostics, citations, and self-healing logic.
    """
    model_chain = model_chain or [os.environ.get("EDITH_MODEL", "gemini-2.5-flash")]
    intent_lower = intent.lower()

    # Match to template
    matched_template = None
    for name, template in INTENT_TEMPLATES.items():
        if any(kw in intent_lower for kw in template["keywords"]):
            matched_template = (name, template)
            break

    # Sign the thought
    sig = thought_signer.sign_thought(
        f"Tab-to-Intent: {intent}",
        grounding=[matched_template[0] if matched_template else "custom"],
    )

    # Generate code via LLM
    try:
        from server.backend_logic import generate_text_via_chain

        template_hint = ""
        if matched_template:
            key = f"{language}_template"
            template_hint = f"\n\nUSE THIS TEMPLATE AS A STARTING POINT:\n{matched_template[1].get(key, '')}"

        prompt = (
            f"RESEARCH INTENT: {intent}\n"
            f"LANGUAGE: {language}\n"
            f"DATA PATH: {data_path or 'placeholder.dta'}\n"
            f"{template_hint}\n\n"
            f"Generate a COMPLETE, RUNNABLE script that:\n"
            f"1. Loads and cleans the data\n"
            f"2. Runs descriptive statistics\n"
            f"3. Tests the hypothesis with appropriate methods\n"
            f"4. Includes all necessary diagnostics\n"
            f"5. Adds comments explaining each step\n"
            f"6. Handles common errors (singular matrix, convergence)\n\n"
            f"Output the FULL script, ready to run."
        )
        code, model = generate_text_via_chain(
            prompt, model_chain,
            system_instruction=(
                "You are a statistical programming expert for political science. "
                "Generate production-quality code with robust error handling. "
                "Use clustered standard errors by default. "
                "Always check assumptions before running models."
            ),
            temperature=0.1,
        )

        return {
            "intent": intent,
            "language": language,
            "template_used": matched_template[0] if matched_template else "custom",
            "code": code,
            "thought_signature": sig["signature"],
            "model": model,
            "requires_approval": True,
        }
    except Exception as e:
        # Fallback: use template directly
        if matched_template:
            key = f"{language}_template"
            code = matched_template[1].get(key, f"* Intent: {intent}")
            return {
                "intent": intent,
                "language": language,
                "template_used": matched_template[0],
                "code": code,
                "thought_signature": sig["signature"],
                "model": "template_fallback",
                "requires_approval": True,
            }
        return {"error": str(e)}


# ═══════════════════════════════════════════════════════════════════
# §3: ARTIFACT PLANS — Blueprint Before Execution
# "She generates an Artifact—a high-level blueprint."
# ═══════════════════════════════════════════════════════════════════

def generate_artifact_plan(
    intent: str,
    data_path: str = "",
    model_chain: list[str] = None,
) -> dict:
    """Generate a research artifact plan before execution.

    Shows: variables, fixed effects, expected pushback,
    citations, and the approval gate.
    """
    model_chain = model_chain or [os.environ.get("EDITH_MODEL", "gemini-2.5-flash")]

    sig = thought_signer.sign_thought(
        f"Artifact Plan: {intent}",
        grounding=["research_skill", "library"],
    )

    try:
        from server.backend_logic import generate_text_via_chain
        prompt = (
            f"RESEARCH INTENT: {intent}\n"
            f"DATA: {data_path}\n\n"
            f"Generate a RESEARCH ARTIFACT PLAN with these sections:\n\n"
            f"## Variables\n"
            f"- Dependent variable(s) and measurement\n"
            f"- Independent variable(s) and measurement\n"
            f"- Controls and why each is needed\n\n"
            f"## Model Specification\n"
            f"- Why this method (not alternatives)\n"
            f"- Fixed effects and clustering strategy\n"
            f"- Robustness checks planned\n\n"
            f"## Anticipated Pushback\n"
            f"- Methodological objections and pre-emptive answers\n"
            f"- Theoretical objections (what would Mettler/Aldrich say?)\n\n"
            f"## Citations\n"
            f"- Papers grounding each methodological choice\n\n"
            f"## Execution Plan\n"
            f"- Steps Winnie will take autonomously\n"
            f"- Points where human approval is required\n"
        )
        plan, model = generate_text_via_chain(
            prompt, model_chain,
            system_instruction=(
                "You are a PhD research advisor creating a detailed execution plan. "
                "Be rigorous about methodology. Anticipate committee objections."
            ),
            temperature=0.2,
        )
        return {
            "intent": intent,
            "plan": plan,
            "thought_signature": sig["signature"],
            "status": "awaiting_approval",
            "model": model,
        }
    except Exception as e:
        return {
            "intent": intent,
            "plan": (
                f"## Artifact Plan: {intent}\n\n"
                f"### Variables\n- DV: [extracted from intent]\n- IV: [extracted from intent]\n\n"
                f"### Model Specification\n- Method: To be determined based on data structure\n\n"
                f"### Execution Plan\n1. Load data from {data_path}\n"
                f"2. Generate descriptive statistics\n3. Run model\n4. Diagnostics\n"
            ),
            "thought_signature": sig["signature"],
            "status": "awaiting_approval",
            "error": str(e),
        }


# ═══════════════════════════════════════════════════════════════════
# §4: SELF-HEALING SCRIPTS — Auto-Fix on Failure
# "If she hits a singular matrix, she self-heals and retries."
# ═══════════════════════════════════════════════════════════════════

# Common errors and their auto-fix strategies
SELF_HEAL_PATTERNS = {
    r"singular matrix|r\(2001\)": {
        "diagnosis": "Singular matrix — likely collinear or constant variables",
        "fixes": [
            "Remove constant variables from the model",
            "Reduce interaction terms (e.g., replace i.year##i.county with i.year i.county)",
            "Increase matsize",
            "Use a simpler random effects structure",
        ],
        "stata_fix": "matsize 11000\n* Remove constant variables:\nforeach var of varlist {ivs} {{\n    quietly summarize `var'\n    if r(sd) == 0 drop `var'\n}}",
        "r_fix": "# Remove constant columns\ndf <- df[, sapply(df, function(x) length(unique(x)) > 1)]",
    },
    r"convergence not achieved|failed to converge": {
        "diagnosis": "Convergence failure — optimizer stuck",
        "fixes": [
            "Switch optimizer (BHHH, BFGS, NR)",
            "Add 'difficult' option",
            "Simplify random effects structure",
            "Scale variables",
        ],
        "stata_fix": "xtmixed {dv} {ivs} || {level2}: , mle technique(bhhh) difficult iterate(100)",
        "r_fix": "m1 <- lmer({formula}, data = df, control = lmerControl(optimizer = 'bobyqa', optCtrl = list(maxfun = 100000)))",
    },
    r"collinear|omitted because of collinearity|dropped.*collinear": {
        "diagnosis": "Collinearity — variables are linearly dependent",
        "fixes": [
            "Run VIF analysis to identify culprits",
            "Drop variables with VIF > 10",
            "Create composite index from collinear variables",
        ],
        "stata_fix": "quietly regress {dv} {ivs}\nestat vif\n* Drop variables with VIF > 10",
        "r_fix": "library(car)\nvif_vals <- car::vif(lm({dv} ~ {ivs}, data = df))\n# Drop: names(vif_vals[vif_vals > 10])",
    },
    r"no observations|0 obs|empty": {
        "diagnosis": "Zero observations after filtering",
        "fixes": [
            "Check subsetting conditions",
            "Verify variable types (string vs numeric)",
            "Check for systematic missingness",
        ],
        "stata_fix": "tab {filter_var}, missing\ncount if !missing({dv})",
        "r_fix": "cat('Complete cases:', sum(complete.cases(df[, c('{dv}', '{ivs}')])))",
    },
    r"type mismatch|not numeric|cannot be used": {
        "diagnosis": "Variable type error",
        "fixes": [
            "Convert string variables to numeric",
            "Encode categorical variables",
            "Check variable labels",
        ],
        "stata_fix": "destring {var}, replace force\nencode {var}, gen({var}_n)",
        "r_fix": "df${var} <- as.numeric(as.character(df${var}))",
    },
}


def _sandbox_run(code: str, language: str, timeout: int = 10) -> dict:
    """Run code in a restricted subprocess sandbox and return result.

    Returns {"success": bool, "stdout": str, "stderr": str, "exit_code": int}
    """
    import tempfile
    cmd_map = {
        "python": ["python3", "-c"],
        "r": ["Rscript", "-e"],
        "stata": None,  # Stata can't be sandboxed easily
    }
    cmd = cmd_map.get(language.lower())
    if not cmd:
        # Can't sandbox this language — skip verification
        return {"success": None, "stdout": "", "stderr": "sandbox_unavailable", "exit_code": -1}

    try:
        result = subprocess.run(
            [*cmd, code],
            capture_output=True, text=True,
            timeout=timeout,
            env={**os.environ, "OPENBLAS_NUM_THREADS": "1"},
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout[:2000],
            "stderr": result.stderr[:2000],
            "exit_code": result.returncode,
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "stdout": "", "stderr": "Execution timed out", "exit_code": -1}
    except FileNotFoundError:
        return {"success": None, "stdout": "", "stderr": f"{cmd[0]} not found", "exit_code": -1}
    except Exception as e:
        return {"success": False, "stdout": "", "stderr": str(e), "exit_code": -1}


def self_heal_script(
    error_output: str,
    original_code: str,
    language: str = "stata",
    model_chain: list[str] = None,
    verify: bool = False,
    max_attempts: int = 3,
) -> dict:
    """Diagnose a script failure and generate a fixed version.

    Matches error patterns, applies known fixes, and regenerates.

    If verify=True, runs the fix in a subprocess sandbox and retries
    up to max_attempts times if the fix itself fails (agentic loop).
    """
    model_chain = model_chain or [os.environ.get("EDITH_MODEL", "gemini-2.5-flash")]

    # Pattern matching
    matched_patterns = []
    for pattern, fix_info in SELF_HEAL_PATTERNS.items():
        if re.search(pattern, error_output, re.IGNORECASE):
            matched_patterns.append(fix_info)

    sig = thought_signer.sign_thought(
        f"Self-heal: {len(matched_patterns)} patterns matched",
        grounding=[p["diagnosis"] for p in matched_patterns],
    )

    def _generate_fix(ctx: dict) -> dict:
        """Generate a fix — LLM for unknown errors, template for known."""
        current_error = ctx.get("_last_error", error_output)
        current_code = ctx.get("_last_code", original_code)
        attempt = ctx.get("_attempt", 1)

        if matched_patterns and attempt == 1:
            # First attempt: use template
            fix = matched_patterns[0]
            fix_key = f"{language}_fix"
            return {
                "diagnosis": fix["diagnosis"],
                "suggested_fixes": fix["fixes"],
                "fixed_code": fix.get(fix_key, ""),
                "patterns_matched": len(matched_patterns),
                "source": "template",
            }

        # LLM fix (for unknown errors, or retries after template failed)
        try:
            from server.backend_logic import generate_text_via_chain
            history_hint = ""
            if attempt > 1:
                history_hint = (
                    f"\n\nPREVIOUS FIX ATTEMPT FAILED with error:\n"
                    f"{current_error[:500]}\n"
                    f"Do NOT repeat the same fix. Try a different approach.\n"
                )
            prompt = (
                f"ERROR OUTPUT:\n{current_error[:1000]}\n\n"
                f"ORIGINAL CODE:\n{current_code[:1500]}\n\n"
                f"{history_hint}"
                f"Diagnose the error and generate a FIXED version of the code.\n"
                f"Language: {language}\n"
                f"Output ONLY the complete fixed script, no explanation."
            )
            fixed, model = generate_text_via_chain(
                prompt, model_chain,
                system_instruction="You are a debugging expert for statistical software.",
                temperature=0.1 + (attempt * 0.1),  # increase creativity on retries
            )
            return {
                "diagnosis": "LLM-diagnosed error" if attempt == 1 else f"LLM retry #{attempt}",
                "fixed_code": fixed,
                "patterns_matched": len(matched_patterns),
                "source": "llm",
                "model": model,
            }
        except Exception as e:
            return {"error": str(e), "fixed_code": ""}

    def _validate_fix(result: dict) -> dict:
        """Validate fix by running in sandbox."""
        code = result.get("fixed_code", "")
        if not code or result.get("error"):
            return {"valid": False, "error": result.get("error", "No code generated")}
        if not verify:
            return {"valid": True, "error": ""}  # skip verification
        sandbox = _sandbox_run(code, language)
        if sandbox["success"] is None:
            # Can't sandbox — treat as valid (user will verify)
            return {"valid": True, "error": "", "sandbox": "unavailable"}
        if sandbox["success"]:
            return {"valid": True, "error": "", "sandbox": "passed"}
        return {"valid": False, "error": sandbox["stderr"][:500]}

    # Run the agentic loop
    try:
        from server.agentic import agentic_loop
        loop_result = agentic_loop(
            action_fn=_generate_fix,
            validator_fn=_validate_fix,
            max_attempts=max_attempts if verify else 1,
            context={"_last_error": error_output, "_last_code": original_code},
        )
        inner = loop_result["result"]
        return {
            "diagnosis": inner.get("diagnosis", "Unknown"),
            "suggested_fixes": inner.get("suggested_fixes", []),
            "fixed_code": inner.get("fixed_code", ""),
            "fix_code": inner.get("fixed_code", ""),  # compat
            "patterns_matched": inner.get("patterns_matched", 0),
            "thought_signature": sig["signature"],
            "model": inner.get("model", inner.get("source", "template")),
            "requires_approval": not loop_result["verified"],
            "verified": loop_result["verified"],
            "attempts": loop_result["attempts"],
            "attempt_history": loop_result["history"],
        }
    except Exception as e:
        # Ultimate fallback — return simple template match
        if matched_patterns:
            fix = matched_patterns[0]
            return {
                "diagnosis": fix["diagnosis"],
                "suggested_fixes": fix["fixes"],
                "fix_code": fix.get(f"{language}_fix", ""),
                "patterns_matched": len(matched_patterns),
                "thought_signature": sig["signature"],
                "requires_approval": True,
                "verified": False,
            }
        return {"error": str(e)}


# ═══════════════════════════════════════════════════════════════════
# §5: RESEARCH MEMOS — Findings + Citations, Not Raw Output
# "She hands you a Research Memo explaining the findings."
# ═══════════════════════════════════════════════════════════════════

def generate_research_memo(
    intent: str,
    code: str,
    output: str,
    model_chain: list[str] = None,
) -> dict:
    """Transform raw statistical output into a research memo.

    The memo explains findings in academic prose, cites relevant
    literature, and flags methodological concerns.
    """
    model_chain = model_chain or [os.environ.get("EDITH_MODEL", "gemini-2.5-flash")]

    sig = thought_signer.sign_thought(
        f"Research Memo: {intent}",
        grounding=["output_analysis"],
    )

    try:
        from server.backend_logic import generate_text_via_chain
        prompt = (
            f"RESEARCH INTENT: {intent}\n\n"
            f"CODE RUN:\n{code[:1000]}\n\n"
            f"RAW OUTPUT:\n{output[:2000]}\n\n"
            f"Generate a RESEARCH MEMO with:\n"
            f"1. **Key Finding**: One sentence summary\n"
            f"2. **Interpretation**: What this means substantively\n"
            f"3. **Statistical Details**: Coefficients, SEs, significance\n"
            f"4. **Diagnostics**: Model fit, assumption checks\n"
            f"5. **Caveats**: Limitations of this analysis\n"
            f"6. **Next Steps**: What to run next\n"
            f"7. **Relevant Literature**: Papers that support/challenge this finding\n\n"
            f"Write in academic prose suitable for a dissertation methods chapter."
        )
        memo, model = generate_text_via_chain(
            prompt, model_chain,
            system_instruction=(
                "You are a research methodology expert writing a concise memo "
                "for a PhD student. Be precise about statistical interpretation. "
                "Never overstate significance."
            ),
            temperature=0.2,
        )
        return {
            "intent": intent,
            "memo": memo,
            "thought_signature": sig["signature"],
            "model": model,
        }
    except Exception as e:
        return {
            "intent": intent,
            "memo": f"## Research Memo: {intent}\n\n[LLM unavailable — raw output attached]\n\n```\n{output[:1000]}\n```",
            "thought_signature": sig["signature"],
            "error": str(e),
        }


# ═══════════════════════════════════════════════════════════════════
# §6: MISSION CONTROL — Asynchronous Agent Manager
# "Dispatch agents to the Bolt. One re-indexes while another simulates."
# ═══════════════════════════════════════════════════════════════════

class MissionControl:
    """The Manager surface — dispatch and track autonomous agents."""

    def __init__(self):
        self._agents: dict[str, dict] = {}
        self._lock = threading.Lock()

    def dispatch_agent(
        self,
        task_type: str,
        description: str,
        params: dict = None,
    ) -> dict:
        """Dispatch an autonomous agent to work in the background."""
        agent_id = f"agent_{int(time.time())}_{len(self._agents)}"

        agent = {
            "id": agent_id,
            "type": task_type,
            "description": description,
            "params": params or {},
            "status": "dispatched",
            "dispatched_at": datetime.now().isoformat(),
            "progress": 0,
            "result": None,
            "thought_chain": [],
        }

        with self._lock:
            self._agents[agent_id] = agent

        # Start background execution
        thread = threading.Thread(
            target=self._execute_agent, args=(agent_id,), daemon=True
        )
        thread.start()

        return {"agent_id": agent_id, "status": "dispatched", "type": task_type}

    def get_agent_status(self, agent_id: str) -> dict:
        with self._lock:
            return self._agents.get(agent_id, {"error": "Agent not found"})

    def list_agents(self) -> list[dict]:
        with self._lock:
            return [
                {k: v for k, v in a.items() if k != "thought_chain"}
                for a in self._agents.values()
            ]

    def get_all_status(self) -> dict:
        with self._lock:
            running = sum(1 for a in self._agents.values() if a["status"] == "running")
            done = sum(1 for a in self._agents.values() if a["status"] == "completed")
            return {
                "total": len(self._agents),
                "running": running,
                "completed": done,
                "failed": len(self._agents) - running - done,
            }

    def _execute_agent(self, agent_id: str):
        """Execute an agent's task."""
        agent = self._agents.get(agent_id)
        if not agent:
            return

        agent["status"] = "running"
        agent["started_at"] = datetime.now().isoformat()

        try:
            task_type = agent["type"]

            if task_type == "reindex":
                result = self._task_reindex(agent)
            elif task_type == "monte_carlo":
                result = self._task_monte_carlo(agent)
            elif task_type == "literature_scan":
                result = self._task_literature_scan(agent)
            elif task_type == "stress_test":
                result = self._task_stress_test(agent)
            elif task_type == "synthesis":
                result = self._task_synthesis(agent)
            else:
                result = {"error": f"Unknown task type: {task_type}"}

            agent["result"] = result
            agent["status"] = "completed"
        except Exception as e:
            agent["result"] = {"error": str(e)}
            agent["status"] = "failed"

        agent["completed_at"] = datetime.now().isoformat()

    def _task_reindex(self, agent: dict) -> dict:
        """Re-index documents on the Bolt."""
        agent["progress"] = 10
        time.sleep(0.1)  # Simulated work
        agent["progress"] = 50
        try:
            from server.completions import incremental_reindex
            result = incremental_reindex()
            agent["progress"] = 100
            return result
        except Exception:
            agent["progress"] = 100
            return {"status": "reindex_queued"}

    def _task_monte_carlo(self, agent: dict) -> dict:
        """Run Monte Carlo simulation."""
        agent["progress"] = 10
        try:
            from server.simulation_deck import AgentBasedModel
            n = agent["params"].get("n_agents", 5000)
            months = agent["params"].get("months", 12)
            abm = AgentBasedModel(n, agent["params"].get("county", "lubbock"))
            abm.populate()
            agent["progress"] = 30

            shock_type = agent["params"].get("shock_type", "snap_cut")
            shock_mag = agent["params"].get("shock_magnitude", 0.15)
            abm.introduce_shock(shock_type, shock_mag)
            agent["progress"] = 40

            result = abm.simulate_months(months)
            agent["progress"] = 100
            return result
        except Exception as e:
            return {"error": str(e)}

    def _task_literature_scan(self, agent: dict) -> dict:
        """Scan literature feeds."""
        agent["progress"] = 50
        try:
            from server.oracle_engine import heartbeat_monitor
            result = heartbeat_monitor.check_now()
            agent["progress"] = 100
            return result
        except Exception as e:
            return {"error": str(e)}

    def _task_stress_test(self, agent: dict) -> dict:
        """Run causal stress test."""
        agent["progress"] = 20
        try:
            from server.causal_engine import stress_test_causal_claim
            cause = agent["params"].get("cause", "charity density")
            effect = agent["params"].get("effect", "SNAP enrollment")
            result = stress_test_causal_claim(cause, effect)
            agent["progress"] = 100
            return result
        except Exception as e:
            return {"error": str(e)}

    def _task_synthesis(self, agent: dict) -> dict:
        """Find cross-domain synthesis."""
        agent["progress"] = 20
        try:
            from server.oracle_engine import find_synthesis_bridges
            result = find_synthesis_bridges(agent["params"].get("topic", ""))
            agent["progress"] = 100
            return result
        except Exception as e:
            return {"error": str(e)}


mission_control = MissionControl()


# ═══════════════════════════════════════════════════════════════════
# §7: RESEARCH SKILL — Learns Your Coding Style
# "Every task matches your existing work perfectly."
# ═══════════════════════════════════════════════════════════════════

class ResearchSkill:
    """Learns and enforces your personal coding/writing style.

    Tracks: variable naming, table formatting, citation style,
    preferred methods, and writing voice.
    """

    DEFAULT_SKILL = {
        "variable_naming": {
            "convention": "snake_case",
            "prefix_dv": "",
            "prefix_iv": "",
            "examples": {
                "voter_turnout": "Voter turnout (0-1)",
                "charity_density": "Charities per 10K pop",
                "snap_enrollment": "SNAP enrollment rate",
                "income_median": "Median household income",
            },
        },
        "table_formatting": {
            "style": "APA",
            "stars": "* p<0.10, ** p<0.05, *** p<0.01",
            "se_format": "parentheses",
            "includes": ["N", "R²", "Cluster FE", "Year FE"],
        },
        "citation_style": "APSA",
        "preferred_methods": [
            "multi-level models (xtmixed/lmer)",
            "difference-in-differences (Callaway-Sant'Anna)",
            "regression discontinuity (rdrobust)",
            "instrumental variables (2SLS)",
        ],
        "writing_voice": {
            "tone": "precise_academic",
            "person": "third_person_passive",
            "hedging": "moderate",
            "examples": [
                "Results suggest that charity density is negatively associated with SNAP enrollment.",
                "The coefficient on the interaction term is statistically significant at the 5% level.",
            ],
        },
        "stata_preferences": {
            "se_type": "cluster",
            "fe_package": "reghdfe",
            "ml_package": "xtmixed",
            "output_format": "esttab",
        },
        "r_preferences": {
            "se_type": "cluster",
            "fe_package": "fixest",
            "ml_package": "lme4",
            "output_format": "stargazer",
        },
    }

    def __init__(self, data_root: str = ""):
        self._data_root = data_root or os.environ.get("EDITH_DATA_ROOT", ".")
        self._skill_path = os.path.join(self._data_root, ".edith_research_skill.json")
        self._skill = self._load_skill()

    def _load_skill(self) -> dict:
        if os.path.exists(self._skill_path):
            try:
                with open(self._skill_path) as f:
                    return json.load(f)
            except Exception:
                pass
        return dict(self.DEFAULT_SKILL)

    def save_skill(self) -> dict:
        os.makedirs(os.path.dirname(self._skill_path) or ".", exist_ok=True)
        with open(self._skill_path, "w") as f:
            json.dump(self._skill, f, indent=2)
        return {"status": "saved", "path": self._skill_path}

    def get_skill(self) -> dict:
        return dict(self._skill)

    def update_skill(self, updates: dict) -> dict:
        """Update specific skill preferences."""
        for key, value in updates.items():
            if key in self._skill:
                if isinstance(self._skill[key], dict) and isinstance(value, dict):
                    self._skill[key].update(value)
                else:
                    self._skill[key] = value
        self.save_skill()
        return {"status": "updated", "skill": self._skill}

    def learn_from_code(self, code: str, language: str = "stata") -> dict:
        """Analyze existing code to learn style preferences."""
        learned = {}
        code_lower = code.lower()

        # Detect naming convention
        vars_found = re.findall(r'\b([a-z][a-z0-9_]+)\b', code)
        if vars_found:
            snake = sum(1 for v in vars_found if "_" in v)
            camel = sum(1 for v in vars_found if re.match(r'^[a-z]+[A-Z]', v))
            learned["naming"] = "snake_case" if snake > camel else "camelCase"

        # Detect SE preferences
        if "robust" in code_lower or "cluster" in code_lower:
            learned["se_type"] = "cluster" if "cluster" in code_lower else "robust"

        # Detect FE packages
        if "reghdfe" in code_lower:
            learned["fe_package"] = "reghdfe"
        elif "areg" in code_lower:
            learned["fe_package"] = "areg"
        if "fixest" in code_lower or "feols" in code_lower:
            learned["r_fe_package"] = "fixest"

        # Detect output format
        if "esttab" in code_lower:
            learned["output_format"] = "esttab"
        elif "outreg" in code_lower:
            learned["output_format"] = "outreg2"
        elif "stargazer" in code_lower:
            learned["r_output_format"] = "stargazer"

        return {"learned_preferences": learned}

    def apply_to_code(self, code: str, language: str = "stata") -> str:
        """Apply your style preferences to generated code."""
        prefs = self._skill.get(f"{language}_preferences", {})

        # Apply SE preference
        if prefs.get("se_type") == "cluster":
            if language == "stata":
                code = re.sub(r',\s*robust\b', ', cluster({cluster_var})', code)
            elif language == "r":
                code = re.sub(r'vcov\s*=\s*"HC1"', 'cluster = ~{cluster_var}', code)

        return code


research_skill = ResearchSkill()


# ═══════════════════════════════════════════════════════════════════
# GLASS BOX §1: LOGIC TRACE — "Rationalization Artifact"
# ═══════════════════════════════════════════════════════════════════

def generate_logic_trace(
    code: str,
    intent: str,
    data_context: str = "",
    model_chain: list[str] = None,
) -> dict:
    """Generate a "Rationalization Artifact" — explain WHY this code was written.

    Reads the ThoughtSignature chain, the matched template, data context,
    and field notes to produce a natural-language methodological audit.

    The user clicks "Logic Trace" in the Cockpit and sees:
        "I used a fixed-effects model here because your 2024 field notes
         from Lubbock suggested county-level variance was non-random.
         A standard OLS would have ignored the 'Charity Gatekeeping' bias
         I detected in the metadata."

    Returns:
        dict with: rationale, method_justification, data_signals,
                   alternative_methods, thought_chain
    """
    model_chain = model_chain or [os.environ.get("EDITH_MODEL", "gemini-2.5-flash")]

    # 1. Read the reasoning chain
    chain = thought_signer.get_chain()
    chain_summary = []
    for step in chain[-5:]:  # Last 5 steps
        chain_summary.append({
            "thought": step.get("thought", ""),
            "grounding": step.get("grounding", []),
        })

    # 2. Detect which template/method was used
    code_lower = code.lower()
    method_detected = "custom"
    method_rationale = ""

    for name, template in INTENT_TEMPLATES.items():
        if any(kw in code_lower for kw in template["keywords"]):
            method_detected = name
            break

    METHOD_RATIONALES = {
        "multi_level_model": (
            "Multi-level modeling accounts for nested data structure "
            "(e.g., individuals within counties). Standard OLS would "
            "violate the independence assumption and underestimate "
            "standard errors."
        ),
        "difference_in_differences": (
            "DiD exploits a natural experiment — a policy change creates "
            "pre/post variation. This requires the parallel trends "
            "assumption, which should be tested."
        ),
        "regression_discontinuity": (
            "RDD uses a threshold/cutoff as a quasi-random assignment "
            "mechanism. Units just above and below the cutoff are "
            "comparable, giving strong internal validity."
        ),
        "instrumental_variables": (
            "IV addresses endogeneity — when the treatment variable is "
            "correlated with unobservable confounders. The instrument "
            "must satisfy relevance and exclusion."
        ),
    }

    method_rationale = METHOD_RATIONALES.get(method_detected, (
        "A custom model was constructed based on the specific "
        "structure of the data and research question."
    ))

    # 3. Detect data-driven signals in the code
    data_signals = []
    if "cluster" in code_lower:
        data_signals.append("Clustered SEs used — data has group structure")
    if "absorb" in code_lower or "fe" in code_lower:
        data_signals.append("Fixed effects absorb unit-level confounders")
    if "robust" in code_lower:
        data_signals.append("Robust SEs guard against heteroskedasticity")
    if "vif" in code_lower:
        data_signals.append("VIF check — testing for collinearity")
    if "icc" in code_lower:
        data_signals.append("ICC computed — variance partition across levels")

    # 4. Alternative methods considered
    alternatives = []
    for name, template in INTENT_TEMPLATES.items():
        if name != method_detected:
            alternatives.append({
                "method": name.replace("_", " ").title(),
                "why_not": f"Not selected for this intent: '{intent[:50]}'",
            })

    # 5. Try LLM-enhanced rationalization if available
    llm_rationale = ""
    try:
        from server.backend_logic import generate_text_via_chain
        prompt = (
            f"INTENT: {intent}\n"
            f"CODE:\n{code[:800]}\n"
            f"METHOD: {method_detected}\n"
            f"DATA CONTEXT: {data_context[:300]}\n\n"
            f"In 3-4 sentences, explain WHY this specific method was chosen "
            f"for this research question. Reference the data structure, "
            f"assumptions required, and any signals in the research context "
            f"that made this the best approach. Write in first person as "
            f"Winnie (the AI research assistant)."
        )
        llm_rationale, _ = generate_text_via_chain(
            prompt, model_chain,
            system_instruction=(
                "You are explaining your methodological reasoning to a "
                "PhD student. Be precise about WHY, not just WHAT."
            ),
            temperature=0.2,
        )
    except Exception:
        llm_rationale = method_rationale

    sig = thought_signer.sign_thought(
        f"Logic Trace: {method_detected} for '{intent[:50]}'",
        grounding=[method_detected] + data_signals[:2],
    )

    return {
        "intent": intent,
        "method_detected": method_detected,
        "method_rationale": method_rationale,
        "llm_rationale": llm_rationale,
        "data_signals": data_signals,
        "alternatives_considered": alternatives,
        "thought_chain": chain_summary,
        "thought_signature": sig["signature"],
        "glass_box": True,
    }
