#!/usr/bin/env python3
"""
Export Utilities — LaTeX, BibTeX, Slides, and Citation Export
=============================================================
Converts Winnie's responses into formats suitable for academic work.

Improvements implemented:
- App #3: Export to LaTeX with \\cite{} commands
- App #8: Citation manager export (BibTeX)
- App #10: Presentation mode (slides from answers)
"""

import re
import json
import time
import hashlib
from pathlib import Path


def answer_to_latex(answer: str, sources: list[dict] = None, title: str = "") -> str:
    """Convert a Winnie answer to a LaTeX document with \\cite{} commands.
    
    Replaces [S1], [S2] etc. with \\cite{authorYear} format.
    Generates a corresponding .bib file content.
    """
    # Generate BibTeX keys from sources
    bib_entries = {}
    citation_map = {}  # [S1] → cite key
    
    for i, s in enumerate(sources or []):
        meta = s.get("meta", {}) or s.get("metadata", {}) or {}
        label = f"[S{i+1}]"
        
        # Build cite key: authorYear
        author = meta.get("author_guess", "").split(",")[0].split(" ")[-1].strip()
        year = str(meta.get("year_guess", ""))[:4]
        title_word = (meta.get("title_guess", "").split()[0] if meta.get("title_guess") else "").lower()
        
        if author and year:
            cite_key = f"{author.lower()}{year}"
        elif title_word and year:
            cite_key = f"{title_word}{year}"
        else:
            cite_key = f"source{i+1}"
        
        # Ensure unique
        base_key = cite_key
        counter = 1
        while cite_key in bib_entries:
            cite_key = f"{base_key}{chr(96 + counter)}"
            counter += 1
        
        citation_map[label] = cite_key
        
        bib_entries[cite_key] = {
            "type": "article",
            "author": meta.get("author_guess", f"Author {i+1}"),
            "title": meta.get("title_guess", f"Source {i+1}"),
            "year": year or "n.d.",
            "journal": meta.get("journal_guess", meta.get("source_file", "")),
            "note": f"Retrieved from Edith corpus, chunk of {meta.get('source_file', 'unknown')}",
        }
    
    # Replace [S#] citations with \cite{}
    latex_text = answer
    for label, key in sorted(citation_map.items(), key=lambda x: -len(x[0])):
        latex_text = latex_text.replace(label, f"\\cite{{{key}}}")
    
    # Convert markdown to LaTeX
    latex_text = _markdown_to_latex(latex_text)
    
    # Build document
    doc_title = title or "Research Notes"
    document = f"""\\documentclass[12pt]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{natbib}}
\\usepackage{{hyperref}}
\\usepackage{{geometry}}
\\geometry{{margin=1in}}

\\title{{{doc_title}}}
\\author{{Generated by Winnie (Edith Research Assistant)}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

{latex_text}

\\bibliographystyle{{apsr}}
\\bibliography{{references}}

\\end{{document}}
"""
    return document


def _markdown_to_latex(text: str) -> str:
    """Convert common markdown formatting to LaTeX."""
    # Headers
    text = re.sub(r'^### (.+)$', r'\\subsubsection{\1}', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'\\subsection{\1}', text, flags=re.MULTILINE)
    text = re.sub(r'^# (.+)$', r'\\section{\1}', text, flags=re.MULTILINE)
    
    # Bold and italic
    text = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', text)
    text = re.sub(r'\*(.+?)\*', r'\\textit{\1}', text)
    
    # Bullet lists
    lines = text.split('\n')
    in_list = False
    result = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('- ') or stripped.startswith('• '):
            if not in_list:
                result.append('\\begin{itemize}')
                in_list = True
            item = stripped[2:]
            result.append(f'  \\item {item}')
        else:
            if in_list:
                result.append('\\end{itemize}')
                in_list = False
            result.append(line)
    if in_list:
        result.append('\\end{itemize}')
    
    return '\n'.join(result)


def sources_to_bibtex(sources: list[dict]) -> str:
    """Generate BibTeX entries from Winnie's sources."""
    entries = []
    for i, s in enumerate(sources or []):
        meta = s.get("meta", {}) or s.get("metadata", {}) or {}
        author = meta.get("author_guess", f"Author{i+1}")
        year = str(meta.get("year_guess", ""))[:4] or "n.d."
        title = meta.get("title_guess", f"Source {i+1}")
        journal = meta.get("journal_guess", "")
        
        key = f"{author.split(',')[0].split()[-1].strip().lower()}{year}"
        
        entry = f"""@article{{{key},
  author = {{{author}}},
  title = {{{title}}},
  year = {{{year}}},
  journal = {{{journal}}},
}}"""
        entries.append(entry)
    
    return "\n\n".join(entries)


def answer_to_slides(answer: str, title: str = "Research Presentation") -> str:
    """Convert a Winnie answer to Beamer (LaTeX slides) format.
    
    Each section/header becomes a slide.
    Bullet points become itemized content.
    """
    slides = []
    current_slide_title = title
    current_content = []
    
    for line in answer.split('\n'):
        stripped = line.strip()
        
        # New section = new slide
        if stripped.startswith('## ') or stripped.startswith('# '):
            # Save previous slide
            if current_content:
                slides.append((current_slide_title, current_content))
            current_slide_title = stripped.lstrip('#').strip()
            # Remove [S#] citations from slide titles
            current_slide_title = re.sub(r'\[S\d+\]', '', current_slide_title).strip()
            current_content = []
        elif stripped.startswith('- ') or stripped.startswith('• '):
            item = stripped[2:]
            # Shorten citation tags for slides
            item = re.sub(r'\[S(\d+)\]', r'[\1]', item)
            current_content.append(item)
        elif stripped and not stripped.startswith('---'):
            # Regular text - truncate for slide format
            if len(stripped) > 120:
                stripped = stripped[:117] + "..."
            current_content.append(stripped)
    
    if current_content:
        slides.append((current_slide_title, current_content))
    
    # Build Beamer document
    beamer = f"""\\documentclass{{beamer}}
\\usetheme{{Madrid}}
\\usecolortheme{{seahorse}}
\\usepackage[utf8]{{inputenc}}

\\title{{{title}}}
\\author{{Professor's Research Assistant (Winnie)}}
\\date{{\\today}}

\\begin{{document}}

\\begin{{frame}}
\\titlepage
\\end{{frame}}

"""
    
    for slide_title, content in slides:
        beamer += f"\\begin{{frame}}{{{slide_title}}}\n"
        if content:
            beamer += "\\begin{itemize}\n"
            for item in content[:6]:  # Max 6 items per slide
                beamer += f"  \\item {item}\n"
            beamer += "\\end{itemize}\n"
        beamer += "\\end{frame}\n\n"
    
    beamer += "\\end{document}\n"
    return beamer


def export_conversation_to_latex(messages: list[dict], sources: list[dict] = None) -> str:
    """Export an entire conversation to LaTeX."""
    sections = []
    for msg in messages:
        if msg.get("role") == "user":
            question = msg.get("content", "")
            sections.append(f"\\section*{{Question}}\n{question}")
        elif msg.get("role") == "assistant":
            answer = msg.get("content", "")
            latex_answer = _markdown_to_latex(answer)
            sections.append(f"\\section*{{Analysis}}\n{latex_answer}")
    
    return f"""\\documentclass[12pt]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{geometry}}
\\geometry{{margin=1in}}

\\title{{Research Session Notes}}
\\author{{Winnie — Edith Research Assistant}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

{'\\n\\n'.join(sections)}

\\end{{document}}
"""
